### ISSUE TITLE
Still doesn't work...

### ISSUE THREAD

**Issue by vihanb** [The-Quill/SE-Chat-Terminal#30] opened 2016-03-05 16:22 UTC
If I have a site with 0 rooms. It still throws an error:

```
/Users/vihan/Downloads/SE-Chat-Terminal-master-4/chat_modules/core.js:121
    var initialRoomId = initialRoom.room_id;
                                   ^

TypeError: Cannot read property 'room_id' of undefined
    at connectDomainRooms (/Users/vihan/Downloads/SE-Chat-Terminal-master-4/chat_modules/core.js:121:36)
    at /Users/vihan/Downloads/SE-Chat-Terminal-master-4/chat_modules/core.js:225:16
    at Array.map (native)
    at Object.start (/Users/vihan/Downloads/SE-Chat-Terminal-master-4/chat_modules/core.js:214:55)
    at Object.<anonymous> (/Users/vihan/Downloads/SE-Chat-Terminal-master-4/start.js:3:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by The-Quill** [comment] 2016-03-05 23:18
Duplicate of #26

**Closed by The-Quill** 2016-03-05 23:18 UTC
